In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
KMC = pd.read_csv(r'C:\Users\shres\Desktop\Datasets\EMNIST Test.csv',header=None)

In [3]:
KMC

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
14795   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14796   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14797   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14798   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14799   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
14795    0    0    0    0    0    0    0  
14796    0    0    0    0    0    0    0  
14797    0    0    0    0    0    0    0  
14798    0    0    0    0    0    0    0  
14799    0    0    0    0    0    0    0  

[14800 rows x 785 columns]

In [4]:
Test = KMC.to_numpy()

In [11]:
Y = Test[:,0]
Y

array([ 1,  1,  1, ..., 19, 19, 19], dtype=int64)

In [10]:
X = (Test[:,1:])/255
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
X.shape

(14800, 784)

In [12]:
centroid = np.random.rand(19,X.shape[1])

array([[0.36080787, 0.79052047, 0.33267314, ..., 0.39155303, 0.69008399,
        0.80837143],
       [0.36725668, 0.95008552, 0.0390593 , ..., 0.26715463, 0.64951069,
        0.68752535],
       [0.71941572, 0.78482169, 0.28296215, ..., 0.14348609, 0.466557  ,
        0.49267074],
       ...,
       [0.71463724, 0.87818694, 0.56166414, ..., 0.49995484, 0.02160987,
        0.30045628],
       [0.63829767, 0.43205845, 0.97325434, ..., 0.38030657, 0.75102732,
        0.12561282],
       [0.77594065, 0.31618051, 0.35989382, ..., 0.34795711, 0.39641451,
        0.24903806]])

In [25]:
def dist(X):
    centroid = np.random.rand(19,X.shape[1])
    clus_matrix1 = np.ones((19,1))
    for p in range(X.shape[0]):
        diff = (centroid - X[p,:])**2
        dist = (np.sqrt(np.sum(diff,axis = 1))).reshape(19,1)
        clus_matrix1 = np.append(clus_matrix1,dist,axis=1)
    clus_matrix = np.delete(clus_matrix1,0,axis=1)
    return clus_matrix

In [26]:
distance = dist(X)

In [29]:
pd.DataFrame(distance)

0          1          2          3          4          5      \
0   15.548732  15.032432  14.900626  14.923929  15.142962  15.480138   
1   15.211432  15.277063  15.132974  15.206739  15.122819  14.954359   
2   15.773545  15.524216  15.531496  15.336964  15.705613  15.638277   
3   15.552906  15.381526  14.977976  15.021472  15.280614  15.289508   
4   15.737677  15.613449  15.419845  15.384977  15.423581  15.565199   
5   15.672948  15.194061  15.561123  15.295687  15.559483  15.483550   
6   15.647291  15.334218  15.467459  15.128601  15.618347  15.627527   
7   15.182080  15.293336  15.096548  15.150181  15.127338  15.375348   
8   14.750995  15.007543  14.692123  14.639810  14.859955  14.808953   
9   15.583672  15.533057  15.284641  14.695679  15.346350  15.342315   
10  14.975364  15.021778  14.798725  14.775826  14.807370  14.932453   
11  15.407157  15.262989  14.790631  14.778650  15.235862  15.238791   
12  15.163825  14.657145  14.838328  14.657482  14.930098  14.997497   
13  15.110169  15.146057  14.958148  14.730066  14.971350  15.109614   
14  14.961992  14.652953  14.785426  14.706756  14.774707  14.620605   
15  15.423285  15.175251  14.837694  14.748094  15.096944  15.069510   
16  15.202686  15.242851  14.859358  15.036696  15.093482  15.260070   
17  15.551377  15.366202  14.905090  15.007816  15.456754  15.171788   
18  15.207742  15.161343  14.765720  14.519555  15.167119  14.879066   

        6          7          8          9      ...      14790      14791  \
0   15.115265  15.227079  15.351187  15.313866  ...  14.985729  15.011613   
1   15.143241  15.189575  15.509938  15.044052  ...  15.589207  15.510108   
2   15.480011  15.617645  15.574585  15.853489  ...  15.556944  15.857605   
3   15.552450  15.268154  15.476788  15.385042  ...  15.469047  15.727836   
4   15.553401  15.567837  15.742986  15.849766  ...  15.638244  15.978569   
5   15.622063  15.618524  15.781580  15.622477  ...  15.747912  15.771024   
6   15.421822  15.551897  15.445800  15.949630  ...  15.442881  15.873043   
7   15.069365  15.163272  15.240696  15.318411  ...  15.178459  15.333884   
8   14.836901  14.999905  14.961534  15.226017  ...  14.857293  15.233088   
9   15.686774  15.377591  15.510915  15.291358  ...  15.288276  15.794191   
10  14.899781  15.143750  14.905914  15.075718  ...  15.072070  15.229003   
11  15.202910  15.178280  15.330355  14.976729  ...  15.155532  15.368968   
12  15.035916  15.015048  15.288368  15.213769  ...  15.242911  15.251465   
13  14.906505  15.082889  15.295202  15.278965  ...  15.239474  15.380839   
14  14.975236  14.604459  15.037722  14.701401  ...  14.675087  14.888236   
15  14.921206  15.116585  15.091743  15.048367  ...  15.248662  15.112448   
16  14.977488  15.221292  15.103150  15.448776  ...  15.308737  15.242767   
17  15.479774  15.270956  15.237030  15.403518  ...  15.388123  15.378066   
18  14.919027  14.835088  15.059690  14.961237  ...  14.944056  15.074493   

        14792      14793      14794      14795      14796      14797  \
0   14.720140  15.190670  14.792743  14.970328  15.340761  15.020113   
1   14.961855  15.322576  15.233646  14.942929  15.287938  15.095903   
2   15.577942  15.770982  15.488045  15.508211  15.641092  15.514789   
3   15.303404  15.443089  15.604544  15.267647  15.099999  15.437473   
4   15.134570  15.684548  15.828306  15.377973  15.695991  15.522882   
5   15.278850  15.593883  15.494263  15.639976  15.687978  15.596750   
6   15.304404  15.721411  15.512010  15.730752  15.275283  15.619978   
7   15.098120  15.506120  15.094628  15.166800  15.213555  15.035739   
8   14.558765  15.001598  14.801257  14.819789  14.940710  14.744383   
9   14.819032  15.644264  15.388638  15.223812  15.540557  15.073802   
10  14.685968  15.206044  15.039696  14.898567  14.939200  14.696058   
11  15.020816  15.426721  15.091370  15.136176  15.374118  15.043185   
12  14.830432  14.921323  14.996113  14.902203  14.875730  14.902452   
13  15.087653  15.

In [28]:
distance.shape

(19, 14800)

In [30]:
clus = np.argmin(distance,axis=0)
clus

array([ 8, 14,  8, ..., 10, 12, 14], dtype=int64)

In [31]:
clus.shape

(14800,)