In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#Importing Libraries

In [2]:
KMC = pd.read_csv(r'C:\Users\shres\Desktop\Datasets\EMNIST Test.csv',header=None)
#Reading and Conversion of CSV File to NumPy Array

In [3]:
KMC

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
14795   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14796   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14797   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14798   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14799   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
14795    0    0    0    0    0    0    0  
14796    0    0    0    0    0    0    0  
14797    0    0    0    0    0    0    0  
14798    0    0    0    0    0    0    0  
14799    0    0    0    0    0    0    0  

[14800 rows x 785 columns]

In [4]:
Test = KMC.to_numpy()

In [5]:
Y = Test[:,0] #Extracting Output
pd.DataFrame(Y)

array([ 1,  1,  1, ..., 19, 19, 19], dtype=int64)

In [6]:
X = (Test[:,1:])/255 #Feature Scaling of Input Data
pd.DataFrame(X)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
K = 19 #Since 19 Possible Outputs are present

In [ ]:
#Code For One Iteration for Debugging and then implementing it in a function

In [37]:
# centroid = X[np.random.choice(X.shape[0],K,replace=False)]
# centroid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
# centroid.shape

(19, 784)

In [39]:
# def dist(X):
#     centroid = X[np.random.choice(X.shape[0],K,replace=False)]
#     clus_matrix1 = np.ones((19,1))
#     for p in range(X.shape[0]):
#         diff = (centroid - X[p,:])**2
#         dist = (np.sqrt(np.sum(diff,axis = 1))).reshape(19,1)
#         clus_matrix1 = np.append(clus_matrix1,dist,axis=1)
#     clus_matrix = np.delete(clus_matrix1,0,axis=1)
#     return clus_matrix

In [40]:
# distance = dist(X)
# pd.DataFrame(distance)

0          1          2          3          4          5      \
0   11.324130  11.501328  10.796905  12.788307  10.146108  13.092712   
1   11.747624  11.350985  10.809060  11.578801  12.378131  10.815332   
2   12.549282  11.743662  11.175473  13.120113  11.095791  13.060253   
3   13.585544  14.080964  11.097539  10.933423  13.044756  12.505291   
4    9.739531  12.552491  10.329892  13.210746  11.863045  12.959091   
5    8.614427  12.636431   9.670680  12.810101  10.374551  11.328388   
6   11.826251  13.552674  13.099341  12.126111  12.222964  12.408454   
7   10.646446  12.080303   9.880776  12.321290  10.048137  11.224137   
8   10.096837  12.086024  10.848339  12.230036  11.687669  10.372375   
9    9.652653  10.980394  10.710365  11.816791  11.745685  11.880786   
10  13.037098  12.358126  11.804138  13.044364  11.286161  14.499552   
11  11.162249  12.768416   8.385220  11.339603  11.693823  10.321543   
12  11.250106  11.263667  11.271571  12.437656  11.446037  10.099106   
13  10.400364  12.369843  11.103730  12.673781  10.413938  12.880261   
14  10.470383  12.086631  11.258895  14.085168  12.086885  12.336452   
15   9.069778  11.973456  10.663443  12.947738   9.602634  12.195991   
16  10.220774  10.784376  10.385045  12.665997  10.303347  11.117645   
17  14.855449  13.008782  13.766393  12.280842  14.012013  14.062415   
18  11.323074  12.341000  11.864761  12.873604  11.397014  11.488421   

        6          7          8          9      ...      14790      14791  \
0   10.558337  10.280055  10.674116  12.430855  ...   9.670296   9.829258   
1   12.673797  11.850977  13.229390  11.832887  ...   9.651489  10.541444   
2   10.587421  12.089364  11.771845  12.524410  ...  10.601758  10.145973   
3   13.132384  13.138763  13.309308  14.289709  ...  11.282027  13.053130   
4    9.097464   9.553590   9.524554  14.022932  ...  12.505694  10.709555   
5    8.523016  10.492499  10.447253  12.754857  ...  12.227577  10.340949   
6   12.861373  13.223820  12.925848  14.120020  ...  12.939894  13.869257   
7   10.726877  11.813829  11.633424  11.737729  ...   9.867342   9.753240   
8   10.069980  11.958046  12.200700  12.158834  ...  11.756382   9.483466   
9    9.441421   9.872952  10.159369  13.215391  ...  12.603425   9.949367   
10  12.406551  13.324260  13.090594  13.905466  ...  11.538940  11.117005   
11   9.674295  11.695627  12.192787  11.756230  ...  12.611768  10.168738   
12  10.647036  11.743176  12.272497  10.348749  ...  13.066368   8.694993   
13  11.760240  11.245730  11.011431  13.370391  ...   9.419769  10.834610   
14  10.069827   9.592571  10.257485  13.298994  ...  12.741916  11.352132   
15  10.314031  10.301126  10.324297  12.776669  ...  10.397995   9.959046   
16  11.170331  11.310585  11.234693  11.224151  ...  11.405133  10.371068   
17  14.739742  14.778806  14.559718  14.149696  ...  12.413725  13.849748   
18  11.390871  12.633265  12.393963  12.576213  ...   8.860197  11.182012   

        14792      14793      14794      14795      14796      14797  \
0   11.276299   8.857407  10.018373  10.098348   9.773478  11.221597   
1    9.176936  10.135285   8.160750   8.900159  10.973808   7.074867   
2   11.702504  10.467329  10.797749  11.321277  10.780916  11.685763   
3   11.145360  13.271449  12.242443  11.339339  12.441782  10.674813   
4   12.350041  11.722688  13.331404  11.025594  11.681420  13.187780   
5   10.125286  11.192678  12.997728   9.643612  11.573726  10.583368   
6   13.847364  13.852842  14.644158  14.235853  13.054157  13.765147   
7   10.058303   8.630343   9.274010   9.008564   9.165011   8.484564   
8   11.241163  11.262680  10.959569  10.182377  12.494544  10.011606   
9   11.608380  11.345147  13.005821  10.830966  11.471264  12.564494   
10  11.693346   9.885081  11.037714  11.248116  11.103057  11.719911   
11  11.487228  11.828703  12.035764   9.808143  12.197401  10.181248   
12  12.500232  11.259614  12.120320  10.657104  12.739409  10.679578   
13  11.473324   9.

In [13]:
# distance.shape

In [41]:
# clus = np.argmin(distance,axis=0)
# clus

array([ 5, 16, 11, ...,  1,  7, 12], dtype=int64)

In [42]:
# clus.shape

(14800,)

In [43]:
# for i in range(K):
#     if len(X[clus == i]) != 0 :
#         centroid[i,:] = (X[clus == i]).mean(axis=0)
# centroid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
# centroid.shape

(19, 784)

In [61]:
def KMC(X,K,iterations) :
    centroid = X[np.random.choice(X.shape[0],K,replace=False)] #Initializing Centroid
    distance1 = np.ones((19,1))
    for i in range(iterations):
        for p in range(X.shape[0]):
            diff = (centroid - X[p,:])**2 
            dist = (np.sqrt(np.sum(diff,axis = 1))).reshape(19,1) #Calculating Distance
            distance1 = np.append(distance1,dist,axis=1)
        distance = np.delete(distance1,0,axis=1)
        clus = np.argmin(distance,axis=0) #Obtaining cluster for each dataset
        for q in range(K):
            if len(X[clus==q]) != 0 : #If a cluster has no element its centroid remains same
                centroid[q,:] = (X[clus == q]).mean(axis=0) #Finiding New Centroid
        distance1 = np.ones((19,1))
    clusters = clus + 1 #Cluster Number (Starting from 1)
    return clusters, centroid

In [108]:
Y_Pred, Centroid = KMC(X,K,100)
pd.DataFrame(Y_Pred)

0
0      19
1      16
2      19
3      13
4      10
...    ..
14795  19
14796  11
14797  17
14798  15
14799  19

[14800 rows x 1 columns]

In [109]:
def inter_nuc_dist(Centroid): #Finding Inter Nuclear Distances
    dist1 = np.ones((K,1))
    for p in range(K):
        diff = (Centroid[p,:] - Centroid)**2
        dist = np.sqrt(np.sum(diff,axis=1).reshape(K,1))
        dist1 = np.append(dist1,dist,axis=1)
    Distances = np.delete(dist1,0,axis=1)
    return Distances

In [110]:
Inter_ND = inter_nuc_dist(Centroid)

In [111]:
pd.DataFrame(Inter_ND)

0         1         2         3         4         5         6   \
0   0.000000  7.575160  6.749718  5.713338  5.032329  5.681827  5.627477   
1   7.575160  0.000000  6.182000  5.824205  6.712373  7.688039  7.492900   
2   6.749718  6.182000  0.000000  6.755156  6.491093  6.411965  5.946107   
3   5.713338  5.824205  6.755156  0.000000  4.583389  6.864948  6.744217   
4   5.032329  6.712373  6.491093  4.583389  0.000000  6.920070  6.524473   
5   5.681827  7.688039  6.411965  6.864948  6.920070  0.000000  7.549434   
6   5.627477  7.492900  5.946107  6.744217  6.524473  7.549434  0.000000   
7   4.769270  6.054248  6.723814  5.788927  5.299858  4.995524  6.848833   
8   7.506052  5.514054  7.455271  4.813445  7.350938  7.219519  8.094068   
9   6.630802  5.432175  5.877292  4.869105  5.184945  6.863135  5.821445   
10  6.316065  5.059153  4.780808  5.518331  5.182705  7.197197  5.350943   
11  7.067468  4.959511  6.733795  3.943222  6.136314  7.497142  7.018997   
12  6.058912  7.666871  5.597584  7.775683  6.940757  7.296700  4.759822   
13  7.770513  6.204872  7.154384  5.204798  7.545066  7.083110  8.184538   
14  6.831302  4.907140  5.403950  5.077551  6.127481  7.764593  6.230729   
15  5.380626  5.600666  7.422741  4.998430  5.213004  6.849547  7.088099   
16  5.641419  6.967707  7.877225  6.745166  6.848383  7.430605  5.500922   
17  5.112547  5.910226  5.783304  5.647601  5.119635  6.060477  6.076699   
18  5.507039  7.138781  5.681568  6.509577  7.062606  5.027083  5.678022   

          7         8         9         10        11        12        13  \
0   4.769270  7.506052  6.630802  6.316065  7.067468  6.058912  7.770513   
1   6.054248  5.514054  5.432175  5.059153  4.959511  7.666871  6.204872   
2   6.723814  7.455271  5.877292  4.780808  6.733795  5.597584  7.154384   
3   5.788927  4.813445  4.869105  5.518331  3.943222  7.775683  5.204798   
4   5.299858  7.350938  5.184945  5.182705  6.136314  6.940757  7.545066   
5   4.995524  7.219519  6.863135  7.197197  7.497142  7.296700  7.083110   
6   6.848833  8.094068  5.821445  5.350943  7.018997  4.759822  8.184538   
7   0.000000  7.026560  5.868624  6.295767  5.984966  6.594467  6.623812   
8   7.026560  0.000000  6.272538  7.054978  5.506604  9.123034  4.406780   
9   5.868624  6.272538  0.000000  4.813543  5.271411  6.619184  6.006678   
10  6.295767  7.054978  4.813543  0.000000  5.366447  5.815241  7.030580   
11  5.984966  5.506604  5.271411  5.366447  0.000000  7.989253  5.599667   
12  6.594467  9.123034  6.619184  5.815241  7.989253  0.000000  9.063804   
13  6.623812  4.406780  6.006678  7.030580  5.599667  9.063804  0.000000   
14  6.388234  5.320040  5.112868  5.062402  5.663832  6.716965  5.028046   
15  4.610543  5.995791  6.093994  6.083355  5.406927  7.400880  6.684490   
16  5.405427  7.918801  6.141662  6.819178  6.801940  5.016454  8.397826   
17  5.254133  6.567112  5.535648  5.178994  4.974185  6.946773  7.061421   
18  5.616450  6.974407  6.246474  6.859156  6.195618  6.157883  6.782745   

          14        15        16        17        18  
0   6.831302  5.380626  5.641419  5.112547  5.507039  
1   4.907140  5.600666  6.967707  5.910226  7.138781  
2   5.403950  7.422741  7.877225  5.783304  5.681568  
3   5.077551  4.998430  6.745166  5.647601  6.509577  
4   6.127481  5.213004  6.848383  5.119635  7.062606  
5   7.764593  6.849547  7.430605  6.060477  5.027083  
6   6.230729  7.088099  5.500922  6.076699  5.678022  
7   6.388234  4.610543  5.405427  5.254133  5.616450  
8   5.320040  5.995791  7.918801  6.567112  6.974407  
9   5.112868  6.093994  6.141662  5.535648  6.246474  
10  5.062402  6.083355  6.819178  5.178994  6.859156  
11  5.663832  5.406927  6.801940  4.974185  6.195618  
12  6.716965  7.400880  5.016454  6.946773  6.157883  
13  5.028046  6.684490  8.397826  7.061421  6.782745  
14  0.000000  5.831382  6.930088  6.694233  6.784594  
15  5.831382  0.000000  5.217837  5.699355  6.824305  
16  6.930088  5.217837  0.000000 

In [112]:
Inter_ND_Sort = np.sort(Inter_ND,axis=1)

In [113]:
pd.DataFrame(Inter_ND_Sort)

0         1         2         3         4         5         6         7   \
0   0.0  4.769270  5.032329  5.112547  5.380626  5.507039  5.627477  5.641419   
1   0.0  4.907140  4.959511  5.059153  5.432175  5.514054  5.600666  5.824205   
2   0.0  4.780808  5.403950  5.597584  5.681568  5.783304  5.877292  5.946107   
3   0.0  3.943222  4.583389  4.813445  4.869105  4.998430  5.077551  5.204798   
4   0.0  4.583389  5.032329  5.119635  5.182705  5.184945  5.213004  5.299858   
5   0.0  4.995524  5.027083  5.681827  6.060477  6.411965  6.849547  6.863135   
6   0.0  4.759822  5.350943  5.500922  5.627477  5.678022  5.821445  5.946107   
7   0.0  4.610543  4.769270  4.995524  5.254133  5.299858  5.405427  5.616450   
8   0.0  4.406780  4.813445  5.320040  5.506604  5.514054  5.995791  6.272538   
9   0.0  4.813543  4.869105  5.112868  5.184945  5.271411  5.432175  5.535648   
10  0.0  4.780808  4.813543  5.059153  5.062402  5.178994  5.182705  5.350943   
11  0.0  3.943222  4.959511  4.974185  5.271411  5.366447  5.406927  5.506604   
12  0.0  4.759822  5.016454  5.597584  5.815241  6.058912  6.157883  6.594467   
13  0.0  4.406780  5.028046  5.204798  5.599667  6.006678  6.204872  6.623812   
14  0.0  4.907140  5.028046  5.062402  5.077551  5.112868  5.320040  5.403950   
15  0.0  4.610543  4.998430  5.213004  5.217837  5.380626  5.406927  5.600666   
16  0.0  5.016454  5.217837  5.405427  5.500922  5.641419  6.059343  6.141662   
17  0.0  4.974185  4.985686  5.112547  5.119635  5.178994  5.254133  5.535648   
18  0.0  4.985686  5.027083  5.507039  5.616450  5.678022  5.681568  6.059343   

          8         9         10        11        12        13        14  \
0   5.681827  5.713338  6.058912  6.316065  6.630802  6.749718  6.831302   
1   5.910226  6.054248  6.182000  6.204872  6.712373  6.967707  7.138781   
2   6.182000  6.411965  6.491093  6.723814  6.733795  6.749718  6.755156   
3   5.518331  5.647601  5.713338  5.788927  5.824205  6.509577  6.744217   
4   6.127481  6.136314  6.491093  6.524473  6.712373  6.848383  6.920070   
5   6.864948  6.920070  7.083110  7.197197  7.219519  7.296700  7.430605   
6   6.076699  6.230729  6.524473  6.744217  6.848833  7.018997  7.088099   
7   5.788927  5.868624  5.984966  6.054248  6.295767  6.388234  6.594467   
8   6.567112  6.974407  7.026560  7.054978  7.219519  7.350938  7.455271   
9   5.821445  5.868624  5.877292  6.006678  6.093994  6.141662  6.246474   
10  5.366447  5.518331  5.815241  6.083355  6.295767  6.316065  6.819178   
11  5.599667  5.663832  5.984966  6.136314  6.195618  6.733795  6.801940   
12  6.619184  6.716965  6.940757  6.946773  7.296700  7.400880  7.666871   
13  6.684490  6.782745  7.030580  7.061421  7.083110  7.154384  7.545066   
14  5.663832  5.831382  6.127481  6.230729  6.388234  6.694233  6.716965   
15  5.699355  5.831382  5.995791  6.083355  6.093994  6.684490  6.824305   
16  6.437710  6.745166  6.801940  6.819178  6.848383  6.930088  6.967707   
17  5.647601  5.699355  5.783304  5.910226  6.060477  6.076699  6.437710   
18  6.157883  6.195618  6.246474  6.509577  6.782745  6.784594  6.824305   

          15        16        17        18  
0   7.067468  7.506052  7.575160  7.770513  
1   7.492900  7.575160  7.666871  7.688039  
2   7.154384  7.422741  7.455271  7.877225  
3   6.745166  6.755156  6.864948  7.775683  
4   6.940757  7.062606  7.350938  7.545066  
5   7.497142  7.549434  7.688039  7.764593  
6   7.492900  7.549434  8.094068  8.184538  
7   6.623812  6.723814  6.848833  7.026560  
8   7.506052  7.918801  8.094068  9.123034  
9   6.272538  6.619184  6.630802  6.863135  
10  6.859156  7.030580  7.054978  7.197197  
11  7.018997  7.067468  7.497142  7.989253  
12  7.775683  7.989253  9.063804  9.123034  
13  7.770513  8.184538  8.397826  9.063804  
14  6.784594  6.831302  6.930088  7.764593  
15  6.849547  7.088099  7.400880  7.422741  
16  7.430605  7.877225  7.918801  8.397826  
17  6.567112  6.694233  6.946773  7.061421  
18  6.85

In [114]:
Inter_ND_Sort1 = Inter_ND_Sort[:,1] #Finding the Minimum Inter Nuclear Distance wrt Each Cluster
pd.DataFrame(Inter_ND_Sort1)

0
0   4.769270
1   4.907140
2   4.780808
3   3.943222
4   4.583389
5   4.995524
6   4.759822
7   4.610543
8   4.406780
9   4.813543
10  4.780808
11  3.943222
12  4.759822
13  4.406780
14  4.907140
15  4.610543
16  5.016454
17  4.974185
18  4.985686

In [115]:
Min_Inter_ND = np.amin(Inter_ND_Sort1) #Finding overall Minimum Inter Nuclear Distance
Min_Inter_ND

3.9432224939131757

In [116]:
def intra_nuc_dist(X,Y_Pred,Centroid): #Calculating Intra Nuclear Distances
    l1 = []
    for p in range(K):
        if X[Y_Pred==p].shape[0] != 0 :
            diff = (X[Y_Pred==p] - Centroid[p,:])**2
            dist1 = np.sqrt(np.sum(diff,axis=1))
            dist2 = (2/X[Y_Pred==p].shape[0])*(np.sum(dist1))
            l1.append(dist2)
    return l1

In [117]:
Intra_ND = intra_nuc_dist(X,Y_Pred,Centroid)

In [118]:
print(Intra_ND)

[20.06581133922893, 18.13480574602766, 20.65058410844292, 15.975900776734683, 19.4883109646312, 20.66554684404914, 19.027649834175577, 20.042245368774644, 16.487171486437823, 17.55908371816562, 18.467148199389293, 20.59206580289972, 22.808710068666844, 14.47722851125349, 18.412364912755905, 17.47803247514245, 18.563988667798547, 17.81653555626844]


In [119]:
len(Intra_ND)

18

In [120]:
Max_Intra_ND = max(Intra_ND) #Finding the Maximum Intra Nuclear Distance
Max_Intra_ND

22.808710068666844

In [121]:
def Dunn_Index(Min,Max): #Calculating Dunn Index
    DI = Min/Max
    return DI

In [122]:
Dunn_Index(Min_Inter_ND,Max_Intra_ND)

0.17288231039992585