In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [53]:
NN_Train = pd.read_csv(r"C:\Users\shres\Desktop\Datasets\EMNIST Train.csv",header=None)
NN_Test = pd.read_csv(r"C:\Users\shres\Desktop\Datasets\EMNIST Test.csv",header=None)

In [54]:
NN_Train

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        7    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2       16    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3       15    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
88795    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88796   21    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88797    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88798   23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88799   12    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
88795    0    0    0    0    0    0    0  
88796    0    0    0    0    0    0    0  
88797    0    0    0    0    0    0    0  
88798    0    0    0    0    0    0    0  
88799    0    0    0    0    0    0    0  

[88800 rows x 785 columns]

In [55]:
NN_Test

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
14795   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14796   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14797   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14798   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14799   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
14795    0    0    0    0    0    0    0  
14796    0    0    0    0    0    0    0  
14797    0    0    0    0    0    0    0  
14798    0    0    0    0    0    0    0  
14799    0    0    0    0    0    0    0  

[14800 rows x 785 columns]

In [56]:
Scaled_Train = NN_Train.iloc[:,1:]/255
Scaled_Test = NN_Test.iloc[:,1:]/255

In [57]:
X1 = Scaled_Train.to_numpy()
X_Test1 = Scaled_Test.to_numpy()
print(X1.shape,"\n",X_Test1.shape)

(88800, 784) 
 (14800, 784)


In [58]:
IM = np.identity(26)
y_class = NN_Train.iloc[:,0]
y_list = []
for i in range(NN_Train.shape[0]) :
    a = y_class[i]-1
    y_list.append(IM[a,:])
Y1 = np.array(y_list)
print(Y1,'\n',Y1.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 
 (88800, 26)


In [59]:
X = X1.T
X_Test = X_Test1.T
Y = Y1.T
print(X.shape,X_Test.shape,Y.shape)

(784, 88800) (784, 14800) (26, 88800)


In [60]:
m = X.shape[0]
n = X.shape[1]
l = Y.shape[0]

In [61]:
np.random.rand(n,l).shape

(88800, 26)

In [62]:
rr = np.array([[1,2,3],[4,5,6]])
np.sum(rr,axis=1)

array([ 6, 15])

In [71]:
def neural_network(iterations,learning_rate,X,Y,X_Test):
    #Initialisation
    m = X.shape[1]
    n = X.shape[0]
    l = Y.shape[0]
    theta1 = 0.001*np.random.rand(n,l)
    bias1 = np.random.rand(l,1)
    theta2 = 0.001*np.random.rand(l,l)
    bias2 = np.random.rand(l,1)
#     dt1 = 0
#     dt2 = 0
#     db1 = 0
#     db2 = 0
    for i in range(iterations):
        #Forward Propagation
        Z2 = np.dot(theta1.T,X) + bias1
        A2 = 1/(1+np.exp(-Z2))
        Z3 = np.dot(theta2.T,A2) + bias2
        A3 = 1/(1+np.exp(-Z3))
        #Backward propagation
        Del3 = A3 - Y
        der = A2 * (1-A2)
        Del2 = np.dot(theta2,Del3) * der
        #Computing Gradients
        dt1 = (1/m) * np.dot(Del2,X.T)
        dt2 = (1/m) * np.dot(Del3,A2.T)
        db1 = (1/m) * (np.sum(Del2,axis=1)).reshape(l,1)
        db2 = (1/m) * (np.sum(Del3,axis=1)).reshape(l,1)
        #Assigning New Hyperparameters
        theta1 = theta1 - dt1.T * learning_rate
        theta2 = theta2 - dt2.T * learning_rate
        bias1 = bias1 - db1 * learning_rate
        bias2 = bias2 - db2 * learning_rate
    Y_T1 = np.dot(theta1.T,X_Test) + bias1
    Y_P1 = 1/(1+np.exp(-Y_T1))
    Y_T2 = np.dot(theta2.T,Y_P1) + bias2
    Y_Prob = 1/(1+np.exp(-Y_T2))
    return Y_Prob

In [72]:
Y_Prob = neural_network(500,0.01,X,Y,X_Test)
Y_Prob

array([[0.03718138, 0.03531705, 0.0429529 , ..., 0.03325933, 0.03952634,
        0.03795745],
       [0.03681348, 0.03497894, 0.04248976, ..., 0.03295351, 0.03912031,
        0.03757699],
       [0.0364669 , 0.03449449, 0.04262094, ..., 0.03232714, 0.03895894,
        0.03729026],
       ...,
       [0.03756986, 0.03580785, 0.04299028, ..., 0.03385613, 0.03977821,
        0.03830166],
       [0.03589591, 0.03400725, 0.04177247, ..., 0.03192871, 0.0382785 ,
        0.03668347],
       [0.03713608, 0.03518697, 0.04319778, ..., 0.03304123, 0.03959411,
        0.03794882]])

In [73]:
Y_Prob.shape

(26, 14800)

In [74]:
Y_Pred2 = np.argmax(Y_Prob,axis=0)
Y_Pred3 = Y_Pred2 + 1
Y_Pred3

array([ 5,  5, 15, ...,  5,  5,  5], dtype=int64)

In [75]:
Y_True = (NN_Test.iloc[:,0]).to_numpy()
Y_True

array([ 1,  1,  1, ..., 19, 19, 19], dtype=int64)

In [76]:
Y33=(Y_Pred3-Y_True).tolist()
Y33

[4,
 4,
 14,
 4,
 4,
 4,
 4,
 4,
 14,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 25,
 4,
 4,
 4,
 14,
 4,
 25,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 14,
 4,
 14,
 4,
 4,
 4,
 4,
 4,
 25,
 4,
 4,
 4,
 4,
 4,
 4,
 14,
 4,
 4,
 14,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 14,
 4,
 14,
 4,
 4,
 4,
 14,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 14,
 14,
 4,
 4,
 4,
 4,
 4,
 25,
 4,
 4,
 4,
 4,
 4,
 4,
 14,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 14,
 14,
 4,
 4,
 4,
 4,
 4,
 4,
 14,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 14,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 14,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 25,
 4,
 4,
 4,
 4,
 25,
 14,
 4,
 4,
 25,
 4,
 4,
 4,
 4,
 4,
 4,
 4

In [77]:
cor = Y33.count(0)
cor

775

In [78]:
Accuracy = (cor/NN_Test.shape[0])*100
Accuracy

5.236486486486487