In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
NN_Train = pd.read_csv(r"C:\Users\shres\Desktop\Datasets\EMNIST Train.csv",header=None)
NN_Test = pd.read_csv(r"C:\Users\shres\Desktop\Datasets\EMNIST Test.csv",header=None)

In [3]:
NN_Train

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        7    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2       16    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3       15    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
88795    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88796   21    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88797    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88798   23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88799   12    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
88795    0    0    0    0    0    0    0  
88796    0    0    0    0    0    0    0  
88797    0    0    0    0    0    0    0  
88798    0    0    0    0    0    0    0  
88799    0    0    0    0    0    0    0  

[88800 rows x 785 columns]

In [4]:
NN_Test

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
14795   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14796   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14797   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14798   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14799   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
14795    0    0    0    0    0    0    0  
14796    0    0    0    0    0    0    0  
14797    0    0    0    0    0    0    0  
14798    0    0    0    0    0    0    0  
14799    0    0    0    0    0    0    0  

[14800 rows x 785 columns]

In [5]:
Scaled_Train = NN_Train.iloc[:,1:]/255
Scaled_Test = NN_Test.iloc[:,1:]/255

In [6]:
X1 = Scaled_Train.to_numpy()
X_Test1 = Scaled_Test.to_numpy()
print(X1.shape,"\n",X_Test1.shape)

(88800, 784) 
 (14800, 784)


In [7]:
IM = np.identity(26)
y_class = NN_Train.iloc[:,0]
y_list = []
for i in range(NN_Train.shape[0]) :
    a = y_class[i]-1
    y_list.append(IM[a,:])
Y1 = np.array(y_list)
print(Y1,'\n',Y1.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 
 (88800, 26)


In [8]:
X = X1.T
X_Test = X_Test1.T
Y = Y1.T
print(X.shape,X_Test.shape,Y.shape)

(784, 88800) (784, 14800) (26, 88800)


In [105]:
def neural_network(iterations,learning_rate,X,Y,X_Test):
    #Initialisation
    m = X.shape[1]
    n = X.shape[0]
    l = Y.shape[0]
    theta1 = 0.001*np.random.rand(n,l)
    bias1 = np.random.rand(l,1)
    theta2 = 0.001*np.random.rand(l,l)
    bias2 = np.random.rand(l,1)
#     dt1 = 0
#     dt2 = 0
#     db1 = 0
#     db2 = 0
    for i in range(iterations):
        #Forward Propagation
        Z2 = np.dot(theta1.T,X) + bias1
        A2 = 1/(1+np.exp(-Z2))
        Z3 = np.dot(theta2.T,A2) + bias2
        A3 = 1/(1+np.exp(-Z3))
        cost = (np.sum((Y)*np.log(A3)+(1-Y)*np.log(1-A3)))*(-1/m)
        #Backward propagation
        Del3 = (A3 - Y) * (A3 * (1-A3))
        Del2 = np.dot(theta2,Del3) * (A2 * (1-A2))
        #Computing Gradients
        dt1 = (1/m) * np.dot(Del2,X.T)
        dt2 = (1/m) * np.dot(Del3,A2.T)
        db1 = (1/m) * (np.sum(Del2,axis=1)).reshape(l,1)
        db2 = (1/m) * (np.sum(Del3,axis=1)).reshape(l,1)
        #Assigning New Hyperparameters
        theta1 = theta1 - dt1.T * learning_rate
        theta2 = theta2 - dt2.T * learning_rate
        bias1 = bias1 - db1 * learning_rate
        bias2 = bias2 - db2 * learning_rate
        if i%10 == 0 :
            print(i,cost)
    Y_T1 = np.dot(theta1.T,X_Test) + bias1
    Y_P1 = 1/(1+np.exp(-Y_T1))
    Y_T2 = np.dot(theta2.T,Y_P1) + bias2
    Y_Prob = 1/(1+np.exp(-Y_T2))
    return Y_Prob

In [107]:
Y_Prob = neural_network(1000,6,X,Y,X_Test)
Y_Prob

0 25.08561482820499
10 7.999716324298785
20 7.555654830033048
30 6.609102011863151
40 4.973750054876117
50 4.873292454592154
60 4.76905185717923
70 4.595652027007731
80 4.4629705759561
90 4.396284525428069
100 4.360110398031691
110 4.337641776184667
120 4.32214888049999
130 4.310661623886478
140 4.301698724441139
150 4.294436624948654
160 4.288376486280695
170 4.283195286066632
180 4.278671641359883
190 4.274645165591744
200 4.270992348282961
210 4.267611231937434
220 4.264411101440397
230 4.261305272212173
240 4.258205984907211
250 4.255020702805864
260 4.251648922496541
270 4.24797850717248
280 4.243881500243771
290 4.239211565928047
300 4.233807092912634
310 4.22750370783684
320 4.220157036661539
330 4.211671449496561
340 4.202024606788985
350 4.191276212863465
360 4.179559211675955
370 4.1670685452714595
380 4.154066823662493
390 4.140889617839975
400 4.127886564221417
410 4.115299585194004
420 4.103185481030994
430 4.091450305031687
440 4.079951560674678
450 4.06856201066322
460 4

array([[6.53755013e-02, 6.74443328e-02, 4.39313569e-02, ...,
        6.10084018e-02, 2.90743299e-02, 6.20310553e-02],
       [6.58317453e-03, 7.85866031e-02, 3.28267763e-02, ...,
        1.50365028e-01, 5.13735517e-02, 1.43251356e-02],
       [9.33478522e-03, 4.65829258e-05, 1.14974157e-01, ...,
        1.43152882e-03, 4.51097200e-02, 6.57337212e-02],
       ...,
       [3.96505960e-03, 4.37528271e-01, 5.11067419e-04, ...,
        3.01387003e-03, 5.56639509e-03, 7.28872626e-03],
       [3.11212714e-02, 3.89244237e-02, 1.48756090e-03, ...,
        5.06170763e-03, 1.53691972e-02, 8.30100297e-03],
       [4.02947727e-03, 2.61430025e-02, 3.47295274e-02, ...,
        1.94324107e-02, 3.42627247e-02, 2.58992112e-02]])

In [108]:
Y_Prob.shape

(26, 14800)

In [109]:
Y_Pred2 = np.argmax(Y_Prob,axis=0)
Y_Pred3 = Y_Pred2 + 1
Y_Pred3

array([13, 24, 21, ..., 19, 10, 21], dtype=int64)

In [110]:
Y_True = (NN_Test.iloc[:,0]).to_numpy()
Y_True

array([ 1,  1,  1, ..., 19, 19, 19], dtype=int64)

In [111]:
Y33=(Y_Pred3-Y_True).tolist()
Y33

[12,
 23,
 20,
 20,
 7,
 13,
 10,
 10,
 10,
 7,
 22,
 10,
 14,
 13,
 7,
 13,
 4,
 10,
 10,
 2,
 7,
 10,
 4,
 25,
 0,
 10,
 7,
 15,
 7,
 10,
 10,
 13,
 21,
 10,
 24,
 10,
 13,
 7,
 13,
 13,
 10,
 4,
 10,
 14,
 20,
 15,
 10,
 20,
 20,
 1,
 13,
 14,
 7,
 13,
 14,
 23,
 7,
 13,
 4,
 20,
 13,
 12,
 20,
 4,
 7,
 12,
 7,
 7,
 13,
 1,
 13,
 4,
 13,
 9,
 18,
 10,
 9,
 7,
 3,
 13,
 14,
 10,
 14,
 14,
 25,
 13,
 14,
 10,
 20,
 25,
 20,
 13,
 7,
 2,
 1,
 14,
 14,
 4,
 20,
 10,
 7,
 7,
 7,
 12,
 13,
 14,
 13,
 1,
 12,
 13,
 25,
 4,
 1,
 1,
 2,
 21,
 25,
 14,
 7,
 9,
 10,
 14,
 23,
 10,
 1,
 12,
 13,
 7,
 14,
 17,
 1,
 4,
 3,
 25,
 1,
 10,
 12,
 13,
 18,
 7,
 20,
 4,
 20,
 14,
 14,
 10,
 13,
 20,
 7,
 24,
 13,
 13,
 14,
 20,
 10,
 22,
 20,
 7,
 13,
 1,
 7,
 13,
 13,
 10,
 22,
 13,
 13,
 14,
 10,
 10,
 4,
 13,
 10,
 7,
 20,
 21,
 2,
 13,
 7,
 22,
 14,
 25,
 7,
 7,
 1,
 7,
 15,
 4,
 15,
 10,
 10,
 20,
 1,
 10,
 0,
 7,
 13,
 12,
 10,
 7,
 1,
 9,
 18,
 12,
 7,
 12,
 10,
 2,
 14,
 9,
 14,
 7,
 14,
 20,
 

In [112]:
cor = Y33.count(0)
cor

7485

In [113]:
Accuracy = (cor/NN_Test.shape[0])*100
Accuracy

50.57432432432433

In [ ]:
# LR = 3 Acc = 31.9
# LR = 5.5 Acc = 49
# LR = 9 Acc = 5.4
# LR = 6 Acc = 50.574