In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
NN_Train = pd.read_csv(r"C:\Users\shres\Desktop\Datasets\EMNIST Train.csv",header=None)
NN_Test = pd.read_csv(r"C:\Users\shres\Desktop\Datasets\EMNIST Test.csv",header=None)

In [4]:
NN_Train

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        7    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2       16    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3       15    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
88795    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88796   21    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88797    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88798   23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88799   12    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
88795    0    0    0    0    0    0    0  
88796    0    0    0    0    0    0    0  
88797    0    0    0    0    0    0    0  
88798    0    0    0    0    0    0    0  
88799    0    0    0    0    0    0    0  

[88800 rows x 785 columns]

In [5]:
NN_Test

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
14795   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14796   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14797   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14798   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14799   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
14795    0    0    0    0    0    0    0  
14796    0    0    0    0    0    0    0  
14797    0    0    0    0    0    0    0  
14798    0    0    0    0    0    0    0  
14799    0    0    0    0    0    0    0  

[14800 rows x 785 columns]

In [6]:
Scaled_Train = NN_Train.iloc[:,1:]/255
Scaled_Test = NN_Test.iloc[:,1:]/255

In [7]:
X1 = Scaled_Train.to_numpy()
X_Test1 = Scaled_Test.to_numpy()
print(X1.shape,"\n",X_Test1.shape)

(88800, 784) 
 (14800, 784)


In [8]:
IM = np.identity(26)
y_class = NN_Train.iloc[:,0]
y_list = []
for i in range(NN_Train.shape[0]) :
    a = y_class[i]-1
    y_list.append(IM[a,:])
Y1 = np.array(y_list)
print(Y1,'\n',Y1.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 
 (88800, 26)


In [9]:
X = X1.T
X_Test = X_Test1.T
Y = Y1.T
print(X.shape,X_Test.shape,Y.shape)

(784, 88800) (784, 14800) (26, 88800)


In [14]:
def neural_network(iterations,learning_rate,X,Y,X_Test):
    #Initialisation
    m = X.shape[1]
    n = X.shape[0]
    l = Y.shape[0]
    theta1 = 0.001*np.ones((n,100))
    bias1 = np.ones((100,1))
    theta2 = 0.001*np.ones((100,l))
    bias2 = np.ones((l,1))
#     dt1 = 0
#     dt2 = 0
#     db1 = 0
#     db2 = 0
    for i in range(iterations):
        #Forward Propagation
        Z2 = np.dot(theta1.T,X) + bias1
        A2 = 1/(1+np.exp(-Z2))
        Z3 = np.dot(theta2.T,A2) + bias2
        A3 = 1/(1+np.exp(-Z3))
        #Backward propagation
        Del3 = A3 - Y
        der = A2 * (1-A2)
        Del2 = np.dot(theta2,Del3) * der
        #Computing Gradients
        dt1 = (1/m) * np.dot(Del2,X.T)
        dt2 = (1/m) * np.dot(Del3,A2.T)
        db1 = (1/m) * (np.sum(Del2,axis=1)).reshape(100,1)
        db2 = (1/m) * (np.sum(Del3,axis=1)).reshape(l,1)
        #Assigning New Hyperparameters
        theta1 = theta1 - dt1.T * learning_rate
        theta2 = theta2 - dt2.T * learning_rate
        bias1 = bias1 - db1 * learning_rate
        bias2 = bias2 - db2 * learning_rate
    Y_T1 = np.dot(theta1.T,X_Test) + bias1
    Y_P1 = 1/(1+np.exp(-Y_T1))
    Y_T2 = np.dot(theta2.T,Y_P1) + bias2
    Y_Prob = 1/(1+np.exp(-Y_T2))
    return Y_Prob

In [15]:
Y_Prob = neural_network(500,0.001,X,Y,X_Test)
Y_Prob

array([[0.0560674 , 0.05381644, 0.05923175, ..., 0.05170511, 0.05733523,
        0.05680813],
       [0.05588751, 0.05364133, 0.05904533, ..., 0.0515346 , 0.05715269,
        0.05662669],
       [0.05596002, 0.05371184, 0.05912057, ..., 0.0516032 , 0.0572263 ,
        0.05669985],
       ...,
       [0.05619943, 0.05394484, 0.05936875, ..., 0.05183004, 0.05746926,
        0.05694134],
       [0.05578753, 0.05354384, 0.05894196, ..., 0.05143951, 0.05705134,
        0.05652591],
       [0.05621929, 0.0539642 , 0.05938928, ..., 0.05184893, 0.05748939,
        0.05696135]])

In [16]:
Y_Prob.shape

(26, 14800)

In [17]:
Y_Pred2 = np.argmax(Y_Prob,axis=0)
Y_Pred3 = Y_Pred2 + 1
Y_Pred3

array([5, 5, 5, ..., 5, 5, 5], dtype=int64)

In [18]:
Y_True = (NN_Test.iloc[:,0]).to_numpy()
Y_True

array([ 1,  1,  1, ..., 19, 19, 19], dtype=int64)

In [19]:
Y33=(Y_Pred3-Y_True).tolist()
Y33

[4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,


In [20]:
cor = Y33.count(0)
cor

800

In [21]:
Accuracy = (cor/NN_Test.shape[0])*100
Accuracy

5.405405405405405