In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
NL_Train = pd.read_csv(r'C:\Users\shres\Desktop\Datasets\EMNIST Train.csv',header=None)
NL_Test = pd.read_csv(r'C:\Users\shres\Desktop\Datasets\EMNIST Test.csv',header=None)
Train = NL_Train.to_numpy()
Test = NL_Test.to_numpy()

In [7]:
NL_Train

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        7    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2       16    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3       15    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
88795    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88796   21    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88797    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88798   23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88799   12    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
88795    0    0    0    0    0    0    0  
88796    0    0    0    0    0    0    0  
88797    0    0    0    0    0    0    0  
88798    0    0    0    0    0    0    0  
88799    0    0    0    0    0    0    0  

[88800 rows x 785 columns]

In [8]:
NL_Test

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
14795   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14796   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14797   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14798   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14799   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
14795    0    0    0    0    0    0    0  
14796    0    0    0    0    0    0    0  
14797    0    0    0    0    0    0    0  
14798    0    0    0    0    0    0    0  
14799    0    0    0    0    0    0    0  

[14800 rows x 785 columns]

In [9]:
IM = np.identity(26)
y_class = Train[:,0]
y_list = []
for i in range(Train.shape[0]) :
    a = y_class[i]-1
    y_list.append(IM[a,:])
Y = np.array(y_list)
print(Y,'\n',Y.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 
 (88800, 26)


In [10]:
X = (Train[:,1:Train.shape[1]])/255
print(X,X.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] (88800, 784)


In [11]:
X_Test = (Test[:,1:Test.shape[1]])/255
print(X_Test,X_Test.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] (14800, 784)


In [27]:
X.shape

(88800, 784)

In [28]:
def neural_network(iterations,learning_rate,X,Y,X_Test):
    m = X.shape[0]
    Weight1 = np.random.rand(X.shape[1],26)
    Bias1 = np.random.rand(X.shape[0],1)
    Weight2 = np.random.rand(26,26)
    Bias2 = np.random.rand(X.shape[0],1)
    for i in range(iterations):
        #Forward Propagation
        Z2 = np.dot(X,Weight1) + Bias1
        A2 = 1/(1+np.exp(-Z2))
        Z3 = np.dot(A2,Weight2) + Bias2
        A3 = 1/(1+np.exp(-Z3))
        #Backward Propagation
        Del3 = A3 - Y
        der = A2*(1-A2)
        Del2 = (np.dot(Del3,Weight2.T))*der
        dW2 = (np.dot(A2.T,Del3))/m
        dW1 = (np.dot(X.T,Del2))/m
        dB2 = (np.sum(Del3))/m
        dB1 = (np.sum(Del2))/m
        #Updating Hyperparameters
        Weight1 = Weight1 - learning_rate*dW1
        Weight2 = Weight2 - learning_rate*dW2
        Bias1 = Bias1 - learning_rate*dB1
        Bias2 = Bias2 - learning_rate*dB2
    Y_T1 = np.dot(X_Test,Weight1)
    Y_Prob1 = 1/(1+np.exp(-Y_T1))
    Y_T2 = np.dot(Y_Prob1,Weight2)
    Y_Prob = 1/(1+np.exp(-Y_T2))
    return Y_Prob

In [29]:
Y_Prob = neural_network(500,0.5,X,Y,X_Test)

In [30]:
Y_Prob

array([[0.99128685, 0.99128685, 0.99134745, ..., 0.99139431, 0.99143557,
        0.99136834],
       [0.99128685, 0.99128685, 0.99134745, ..., 0.99139431, 0.99143557,
        0.99136834],
       [0.99128685, 0.99128685, 0.99134745, ..., 0.99139431, 0.99143557,
        0.99136834],
       ...,
       [0.99128685, 0.99128685, 0.99134745, ..., 0.99139431, 0.99143557,
        0.99136834],
       [0.99128685, 0.99128685, 0.99134745, ..., 0.99139431, 0.99143557,
        0.99136834],
       [0.99128685, 0.99128685, 0.99134745, ..., 0.99139431, 0.99143557,
        0.99136834]])

In [31]:
Y_Prob.shape

(14800, 26)